name: Deploy Artifacts

on:
  push:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "."
          clean: false

      - name: Pre-Deploy
        run: |
          chmod +x ./.github/scripts/preDeploy.sh
          ./.github/scripts/preDeploy.sh

      - name: Deploy
        env:
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        run: |
          chmod +x ./.github/scripts/deploy.sh
          ./.github/scripts/deploy.sh

      - name: Post-Deploy
        run: |
          chmod +x ./.github/scripts/postDeploy.sh
          ./.github/scripts/postDeploy.sh
